import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { getSiteSettings } from "@/get-api-data/settings";
import VisitorsRecord from "@/auth/visitorsRecord";
import NavbarContainer from "@/components/header/navbar";
import  TopBannerContainer  from "@/components/header/topbanner";
import { ReduxProvider } from "@/redux/provider";
import  PreLoader  from "@/components/common/PreLoader";
import CartProvider from "@/components/cart/CartProvider";
import WishlistProvider from '@/components/wishlist/WishlistProvider';
import { Toaster } from 'react-hot-toast';
import SessionLoader from "@/redux/SessionLoader";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-outfit",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settingsData = await getSiteSettings();
  const preloadedState = { settingsReducer: settingsData };

  return (
    <html lang="en">
      <body
        className={`${outfit.className} antialiased`}
      >
        <PreLoader color={settingsData.primaryColor} />
        <ReduxProvider preloadedState={preloadedState}> 
          <CartProvider>
            <WishlistProvider>
              <TopBannerContainer /> 
              <NavbarContainer />
              <Toaster position="top-center" reverseOrder={false} />
              <SessionLoader />
              {children}
              <VisitorsRecord />
            </WishlistProvider>
          </CartProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}